version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    networks:
      - app-network

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: npm run dev --prefix backend
    ports:
      - "3000:3000"
      - "8080:8080"
    volumes:
      - ./backend:/app:cached
      - backend_node_modules:/app/node_modules
    networks:
      - app-network
    depends_on:
      - devcontainer

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app:cached
      - frontend_node_modules:/app/node_modules
    networks:
      - app-network
    depends_on:
      - devcontainer

volumes:
  backend_node_modules:
  frontend_node_modules:

networks:
  app-network:
    driver: bridge